# Change these first
owner: gestudio # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Flylogs
    url: https://www.flylogs.com
  - name: Authentication Server
    url: https://www.flylogs.com/users/login.json
    method: POST
    body: '{ "data[User][email]": "ping@test.flylogs.com", "data[User][password]": "123456" }'
    expectedStatusCodes: 
      - 200
  - name: Flylogs Barcelona
    url: https://bcn.flylogs.com
  - name: Flylogs New York
    url: https://us.flylogs.com
  - name: Flylogs Frankfurt
    url: https://fra.flylogs.com
    expectedStatusCodes: 
      - 403
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.flylogs.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.flylogs.com/img/logo.png
  name: Flylogs Status
  introTitle: "**Flylogs** services status page"
  introMessage: This is a service status page which uses **real-time** data to display service status.
  css: "body{background:#fff;} nav{ background: #0073d5 !important; } nav a{color: #fff;} [aria-current]{border-bottom-color:#f7b731}"
  links:
    - rel: stylesheet
      href: https://static.flylogs.com/flylogs-status.css
  navbar:
    - title: Status
      href: /
    - title: News
      href: https://www.flylogs.com/news
    - title: Contact
      href: https://www.flylogs.com/home/contact
    - title: Login
      href: https://www.flylogs.com/users/login

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
