# Change these first
owner: gestudio # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Flylogs
    url: https://www.flylogs.com
#  - name: Authentication Server
#    url: https://www.flylogs.com/users/login
#    method: POST
#    body: '{ "data[User][email]": "alumna@test.flylogs.com", "data[User][password]": "123456" }'
#    expectedStatusCodes: 
#      - 302
  - name: Flylogs API
    url: https://api.flylogs.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.flylogs.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.flylogs.com/img/logo.png
  name: Flylogs Status
  introTitle: "**Flylogs** services status page"
  introMessage: This is a service status page which uses **real-time** data to display service status.
  css: "body{background:#fff;} nav { background: #0073d5!important } nav a{color:#fff}"
  navbar:
    - title: Status
      href: /
    - title: News
      href: https://www.flylogs.com/news
    - title: Contact
      href: https://www.flylogs.com/home/contact
    - title: Login
      href: https://www.flylogs.com/users/login

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
NOTIFICATION_SMS_OVH: true
NOTIFICATION_SMS_FROM: FLYLOGS.COM
NOTIFICATION_SMS_TO: +0034674612168
NOTIFICATION_SMS_OVH_APP_KEY: yIDCSgjunTNTjtyG
NOTIFICATION_SMS_OVH_APP_SECRET: RfU9iNYmfguXl27Vsc1f3j9xF4EK1ynz
NOTIFICATION_SMS_OVH_CONSUMER_KEY: vNzGFeWYTeIVemV6FszkJDPh1jekO9HA
NOTIFICATION_SMS_OVH_ACCOUNT: sms-gi2097-1
NOTIFICATION_SMS_OVH_HOST: eu.api.ovhcom
